import streamlit
streamlit.title('Indian Oreo  Healthy Diner')
streamlit.header('Breakfast Menu') 
streamlit.text('Idli')
streamlit.text('Dosa')
streamlit.text('Upma')
streamlit.text('Pongal')
streamlit.text('Poori')
streamlit.text('Tea')
streamlit.text('Cofee')

streamlit.header('Make Your Orio') 
streamlit.text('🍌 Build Your Own Fruit Smoothie 🥝🍇')
streamlit.text('🥝🍇 kale Spinach & Rocket Smoothie 🍌🥭')
streamlit.text('🍌🥭Avacado Upma smoothie 🥝🍇')
